### PR TITLE
Issue #2645458 by smaz, kmoll: update render trait to handle #item_at…

### PR DESCRIPTION
**Pull request by kmoll**
…tributes array element that image_formatter expects

### CODE REVIEW

**Comment by davereid** [comment]
Would this be more appropriate to do in ImageFieldFormatter?

**Comment by kmoll** [comment]
@davereid I would think that might be a better idea.  I am still a little confused why the ImageFieldFormatter uses #item_attributes over #attributes.  It seems to be the only place where this is the case.  I think if its possible, we update that.  If there are good reasons why its that way, then we would have to handle here, I think.  Let me know your thoughts.

**Comment by davereid** [comment]
The core image field formatters require #item_attributes to be set, which is strange, but there's not much we can do about that from Entity Embed's side of things, we can only ensure the correct values are set.

**Comment by slashrsm** [comment]
Unfortunately we can't move this as we add align, caption, ... classes after formatter plugin has returned the render array. Looking at test fails now.

**Comment by slashrsm** [comment]
Attempt to fix test: https://www.drupal.org/node/2645458#comment-11117123

**Comment by davereid** [comment]
Closing as this was fixed via Drupal.org

**Pull request closed without merging**
