### PR TITLE
Fix conflict with Embed module button configuration entity.

### PR DESCRIPTION
**Pull request by davereid**
This shouldn't prevent any exports from working since this doesn't change the config entity filenames at all. Just prevents the menu paths from conflicting.

### CODE REVIEW

**Comment by cs-shadow** [comment]
Since we've changed the id of the config entity, we'll need to modify it in the places where its being used as well and that should fix the failing tests.

From a quick glance, we need to fix the tests at least in https://github.com/drupal-media/entity_embed/blob/8.x-1.x/src/Tests/EmbedButtonCrudTest.php#L38, https://github.com/drupal-media/entity_embed/blob/8.x-1.x/src/Plugin/CKEditorPlugin/DrupalEntity.php#L65 and https://github.com/drupal-media/entity_embed/blob/8.x-1.x/src/Form/EmbedButtonForm.php#L322.

**Comment by davereid** [comment]
@cs-shadow Want to give this a look-over again, should resolve everything now. I did a code search for any remaining instances of embed_button that didn't get changed to entity_embed_button.

**Comment by cs-shadow** [comment]
Yep, looks good now. :+1:

**Comment by jonhattan** [comment]
I think this PR introduced a regression. https://www.drupal.org/node/2548987

**Pull request merged**
