### PR TITLE
Attempt to fail tests.

### PR DESCRIPTION
**Pull request by davereid**

### CODE REVIEW

**Comment by davereid** [comment]
Hmmmm.... EntityEmbedDialogTest is not getting run.

**Comment by davereid** [comment]
Oh, that file is local for me for some reason.

**Comment by cs-shadow** [comment]
@davereid thats because we don't have a EntityEmbedDialogTest (yet). I was blocked by this issue long back: https://www.drupal.org/node/2328659

Will need to tweak a couple of things in the code from that issue if you still want to try that out.

**Comment by davereid** [comment]
Ah, I'm going to propose adding it back in at least for the test coverage for access to the embed form.

**Comment by cs-shadow** [comment]
@davereid Yep, would definitely like that.

PS: Just to clarify, we wouldn't be adding it "back" per se since it was never added in the first place. I'll try see if that form post issue is resolved now.

**Pull request closed without merging**
